feat: prepare for deployment

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -1,5 +1,6 @@
 FROM dunglas/frankenphp:1-php8.3 AS frankenphp_upstream
 
+### Base Image ###############################################################
 FROM frankenphp_upstream AS frankenphp_base
 
 WORKDIR /app
@@ -25,15 +26,42 @@ RUN install-php-extensions \
 
 # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
 ENV COMPOSER_ALLOW_SUPERUSER=1
+ENV SERVER_NAME=":80"
 
-COPY ./.docker/franken/php/conf.d/ /usr/local/etc/php/conf.d/
+COPY --link .docker/php/app.ini $PHP_INI_DIR/conf.d/
+COPY --link --chmod=755 .docker/franken/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
+COPY --link .docker/franken/Caddyfile /etc/caddy/Caddyfile
+
+ENTRYPOINT ["docker-entrypoint"]
 
 HEALTHCHECK --start-period=60s CMD curl -f http://localhost:2019/metrics || exit 1
 CMD [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile" ]
 
-# Dev Image
+### Dev Image ################################################################
 FROM frankenphp_base AS frankenphp_dev
-
 RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
-
 CMD [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--watch" ]
+
+### Prod Image ###############################################################
+FROM frankenphp_base AS frankenphp_prod
+ENV APP_ENV=prod
+RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
+COPY --link .docker/php/app.prod.ini $PHP_INI_DIR/conf.d/
+
+# prevent the reinstallation of vendors at every changes in the source code
+COPY --link composer.* symfony.* ./
+RUN set -eux; \
+	composer install --no-cache --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress
+
+# copy sources
+COPY --link . ./
+
+# cleanup
+RUN rm -rf .docker .github
+
+RUN set -eux; \
+	mkdir -p var/cache var/log; \
+	composer dump-autoload --classmap-authoritative --no-dev; \
+	composer dump-env prod; \
+	composer run-script --no-dev post-install-cmd; \
+	chmod +x bin/console; sync;
